-- Script-review state machine + classified failures.
--
-- New project status values (status column is unconstrained TEXT, so no
-- check-constraint change is needed; documenting them here):
--
--   draft           Project created, scenes not yet generated by Claude.
--   script-review   Claude has produced scenes; user must approve before
--                   image generation begins. (Replaces the previous
--                   'scripted' state, which is preserved for legacy rows.)
--   images-pending  User approved the script; per-scene image jobs queued.
--   images-ready    All scenes have at least one variant; user picks one.
--   generating      User clicked Generate; voice + Seedance running.
--   assembling      All scene videos done; FFmpeg final assembly running.
--   complete        Final MP4 on R2.
--   failed          Terminal failure with error_message populated.
--
-- Per-scene failure classification: stable code so the UI can show
-- explanatory copy ("content filter rejected your prompt", "rate limit
-- hit, retry in a moment", etc.) instead of dumping raw provider errors.
ALTER TABLE scenes
  ADD COLUMN IF NOT EXISTS error_code TEXT;

-- Backfill legacy 'scripted' rows that have no images yet to the new
-- 'script-review' state so they pick up the approval gate too. Rows that
-- already have at least one scene image are left alone -- they were
-- effectively past the review gate under the old flow.
UPDATE projects p
SET    status = 'script-review'
WHERE  p.status = 'scripted'
  AND  NOT EXISTS (
    SELECT 1 FROM scene_images si
    JOIN scenes s ON s.id = si.scene_id
    WHERE s.project_id = p.id
  );
